apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-dalston
  namespace: dalston
spec:
  storageClassName: database
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi